"""empty message

Revision ID: 8a7b9c83eb8b
Revises: 
Create Date: 2024-10-31 20:31:35.565769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7b9c83eb8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('game',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['section.name'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('section')
    # ### end Alembic commands ###
